# Numpy

<div>
<img src="images/numpy_logo.png" width="250"/>
</div>

## ¿Qué es NumPy?

- Definición y propósito: NumPy es la librería fundamental para el cálculo numérico en Python. Permite trabajar con arrays multidimensionales de manera eficiente y ofrece una gran variedad de funciones matemáticas, estadísticas y de álgebra lineal.


- Por qué es importante: Python, por defecto, no está diseñado para manejar grandes volúmenes de datos numéricos de manera rápida y eficiente, pero NumPy resuelve este problema. Comparado con listas de Python, los arrays de NumPy son más rápidos y ocupan menos espacio en memoria.

Viendo un ejemplo:


In [54]:
# Importamos numpy como "np" por convención
import numpy as np

# Sin NumPy
list_a = [1, 2, 3]
list_b = [4, 5, 6]
result = [list_a[i] + list_b[i] for i in range(len(list_a))]
print(result)

# Con NumPy
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
result = array_a + array_b  # Mucho más simple y eficiente
print(result)

[5, 7, 9]
[5 7 9]


## Instalación

In [28]:
# Para python instalado
# !pip install numpy

In [29]:
# Para anaconda instalado
# !conda install numpy

Versión instalada

In [10]:
import numpy as np
print(np.__version__)

1.21.3


## Creación de Arrays

### Array 1D

Es un array de una dimensión similar a una lista de Python, pero es mucho más eficiente para grandes cantidades de datos numéricos.

In [13]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

### Array 2D y más...

Es un array de una dimensión similar a una lista de Python, pero es mucho más eficiente para grandes cantidades de datos numéricos.

In [14]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [15]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Funciones útiles para crear arrays

Introduce funciones clave para crear arrays rápidamente:
- np.zeros(): Crea un array de ceros.
- np.ones(): Crea un array de unos.
- np.arange(): Crea un array con un rango de valores, similar a range() en Python.
- np.linspace(): Crea un array con números equidistantes entre un intervalo

In [16]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

In [18]:
range_arr = np.arange(0, 10, 2)
range_arr

array([0, 2, 4, 6, 8])

In [19]:
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Bonus:
- np.eye(): Para matrices identidad.
- np.random.rand(): Para arrays de números aleatorios.

In [20]:
identidad = np.eye(3)
identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
random_array = np.random.rand(3, 3)
random_array

array([[0.72786478, 0.97927433, 0.37803574],
       [0.5481126 , 0.96402757, 0.96844708],
       [0.92514652, 0.5113198 , 0.57597738]])

## Operaciones básicas con Arrays

### Operaciones matemáticas elementales

NumPy permite realizar operaciones matemáticas de manera eficiente entre arrays y escalares, lo cual es más rápido que usar bucles en Python.

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [23]:
suma = a + b
suma

array([5, 7, 9])

In [24]:
resta = a - b
resta

array([-3, -3, -3])

In [25]:
producto = a * b
producto

array([ 4, 10, 18])

In [26]:
division = a / b
division

array([0.25, 0.4 , 0.5 ])

También puedes sumar, restar, multiplicar o dividir arrays por un escalar

In [27]:
a = np.array([1, 2, 3])
b = a * 2
b

array([2, 4, 6])

### Indexación y slicing

Acceder a elementos

In [30]:
a = np.array([1, 2, 3, 4])
print(a[0])   # Primer elemento
print(a[-1])  # Último elemento

1
4


Slicing en arrays 1D y 2D

In [31]:
a = np.array([1, 2, 3, 4, 5])
print(a[1:4])  # Elementos desde el índice 1 hasta el 3

[2 3 4]


In [32]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 1])  # Elemento en la primera fila, segunda columna
print(b[:, 1])  # Segunda columna de todas las filas
print(b[1:3, 1:3])  # Submatriz 2x2 desde el centro

2
[2 5 8]
[[5 6]
 [8 9]]


## Propiedades y Métodos útiles

### Shape

In [33]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape) 

(3, 2)


### Size

In [35]:
print(a.size)

6


### Dtype

In [38]:
int_array = np.array([1, 2, 3], dtype='int32')
float_array = np.array([1.0, 2.0, 3.0], dtype='float64')
object_array = np.array([1.0, 2.0, 3.0], dtype='object')
print(int_array.dtype)
print(float_array.dtype)
print(object_array.dtype)

int32
float64
object


### Cambiar la forma de los arrays

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = a.reshape((2, 3))  # Cambia a 2 filas y 3 columnas
print(print)
print(reshaped_array)

<built-in function print>
[[1 2 3]
 [4 5 6]]


---

## Ejemplo de uso: Análisis de temperaturas en diferentes ciudades

Vamos a simular un análisis de temperaturas diarias (en grados Celsius) en varias ciudades durante una semana.

Usaremos NumPy para crear arrays, hacer cálculos estadísticos y manipular los datos de manera eficiente.

### Paso 1: Crear un array con los datos de temperatura

Supongamos que tenemos las temperaturas diarias (en °C) de 4 ciudades durante 7 días.

In [44]:
# Array 2D donde cada fila es una ciudad y cada columna representa un día
temperaturas = np.array([
    [15, 18, 20, 22, 19, 17, 16],  # Ciudad 1
    [22, 21, 20, 23, 24, 22, 21],  # Ciudad 2
    [12, 14, 16, 13, 11, 12, 14],  # Ciudad 3
    [30, 32, 31, 29, 28, 30, 31]   # Ciudad 4
])

print("Datos de temperaturas (°C):")
print(temperaturas)

Datos de temperaturas (°C):
[[15 18 20 22 19 17 16]
 [22 21 20 23 24 22 21]
 [12 14 16 13 11 12 14]
 [30 32 31 29 28 30 31]]


### Paso 2: Calcular estadísticas básicas

Ahora vamos a calcular algunas estadísticas importantes:

- La temperatura media de cada ciudad durante la semana.
- La temperatura máxima y mínima de cada ciudad.
- La desviación estándar de las temperaturas (variabilidad).

In [61]:
# Media de las temperaturas por ciudad (media de cada fila)
media_por_ciudad = np.mean(temperaturas, axis=1)
print("Media de temperaturas por ciudad (°C):")
print(media_por_ciudad)

Media de temperaturas por ciudad (°C):
[19.28571429 21.85714286 13.14285714 30.14285714]


In [62]:
# Temperatura máxima por ciudad
max_por_ciudad = np.max(temperaturas, axis=1)
print("Temperatura máxima por ciudad (°C):")
print(max_por_ciudad)

Temperatura máxima por ciudad (°C):
[25 24 16 32]


In [63]:
# Temperatura mínima por ciudad
min_por_ciudad = np.min(temperaturas, axis=1)
print("Temperatura mínima por ciudad (°C):")
print(min_por_ciudad)

Temperatura mínima por ciudad (°C):
[15 20 11 28]


In [64]:
# Desviación estándar por ciudad (variabilidad de temperaturas)
std_por_ciudad = np.std(temperaturas, axis=1)
print("Desviación estándar de temperaturas por ciudad (°C):")
print(std_por_ciudad)

Desviación estándar de temperaturas por ciudad (°C):
[3.80654646 1.2453997  1.55182578 1.2453997 ]


### Paso 3: Sumar una constante a los datos (Broadcasting)

Supongamos que queremos sumar un ajuste de +1°C a todas las temperaturas, por ejemplo, para compensar un error en la medición.

In [65]:
# Usar broadcasting para sumar 1°C a todas las temperaturas
ajustadas = temperaturas + 1
print("Temperaturas ajustadas (+1°C):")
print(ajustadas)

Temperaturas ajustadas (+1°C):
[[16 19 26 26 20 18 17]
 [23 22 21 24 25 23 22]
 [13 15 17 14 12 13 15]
 [31 33 32 30 29 31 32]]


### Paso 4: Seleccionar y modificar datos específicos (indexación y slicing)

Ahora vamos a seleccionar y modificar ciertas partes del array:

- Obtener las temperaturas del tercer día para todas las ciudades.
- Modificar las temperaturas de la primera ciudad cambiando el tercer y cuarto día a 25°C.

In [66]:
# Seleccionar las temperaturas del tercer día para todas las ciudades
dia_3_temperaturas = temperaturas[:, 2]  # Todas las filas, tercera columna
print("Temperaturas del tercer día en todas las ciudades:")
print(dia_3_temperaturas)

Temperaturas del tercer día en todas las ciudades:
[25 20 16 31]


In [67]:
# Modificar el tercer y cuarto día de la primera ciudad
temperaturas[0, 2:4] = 25
print("Temperaturas después de modificar el tercer y cuarto día de la primera ciudad:")
print(temperaturas)

Temperaturas después de modificar el tercer y cuarto día de la primera ciudad:
[[15 18 25 25 19 17 16]
 [22 21 20 23 24 22 21]
 [12 14 16 13 11 12 14]
 [30 32 31 29 28 30 31]]


### Paso 5: Cambiar la forma del array (reshape)

Si queremos cambiar la organización de los datos para otros cálculos o gráficos, podemos cambiar la forma del array. Por ejemplo, podemos reorganizar los datos en una estructura de 2x14 (dos grupos de 14 días).

In [68]:
# Cambiar la forma de los datos a un array de 2 filas y 14 columnas
reshaped = temperaturas.reshape((2, 14))
print("Datos de temperatura reorganizados (2x14):")
print(reshaped)

Datos de temperatura reorganizados (2x14):
[[15 18 25 25 19 17 16 22 21 20 23 24 22 21]
 [12 14 16 13 11 12 14 30 32 31 29 28 30 31]]


### Paso 6: Calcular la correlación entre las ciudades (función avanzada)

Finalmente, vamos a calcular la correlación entre las ciudades para ver si hay patrones similares en sus temperaturas.

In [69]:
# Calcular la correlación entre las ciudades
correlacion = np.corrcoef(temperaturas)
print("Correlación entre las ciudades:")
print(correlacion)

Correlación entre las ciudades:
[[ 1.         -0.05165891  0.47676999 -0.15928165]
 [-0.05165891  1.         -0.87645635 -0.90789474]
 [ 0.47676999 -0.87645635  1.          0.72862034]
 [-0.15928165 -0.90789474  0.72862034  1.        ]]
